name: "Run TODO to Issue"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@master"
        env:
          MANUAL_COMMIT_REF:
            ${{ inputs.MANUAL_COMMIT_REF }}
          MANUAL_BASE_REF:
            ${{ inputs.MANUAL_BASE_REF }}
        with:
          PROJECTS_SECRET: ${{ secrets.PROJECTS_SECRET }}
